class NotLoggedIn(Exception):
    pass


class FailedCall(Exception):
    pass
